"""Editable content for the Mutual Futures public workbench."""
SITE = {
 'name':'Mutual Futures', 'owner':'Luke Nathan Hayes', 'date':'18 September 2026',
 'url':'https://auraofintelligence.github.io/mutual-futures/',
 'repo':'https://github.com/auraofintelligence/mutual-futures',
 'description':'Generational business handovers and civilisation upgrades through shared ownership, AI, robotics and extended reality (XR) just-in-time learning. Explore the proposal, sources and tools.',
 'topics':['mutual-wealth','business-succession','cooperatives','workforce-transition','try-everything-once','intermittent-retirement','universal-intelligence','adequate-income','sovereign-ai','digital-twins','legal-reflection','existential-resilience','civic-health','queensland','oceania','gajra-earth','aura-of-intelligence','kardashev','world-travel','github-pages']
}
def sec(title, text='', **kw): return dict(title=title,text=text,**kw)
def card(title,text,href=None): return dict(title=title,text=text,href=href)
PROJECTS = [
 dict(id='P01',title='Strange but True',url='https://auraofintelligence.github.io/strange-but-true/index.html',repo='strange-but-true',role='Everyday tech, art and ideas',text='The grounded encounter: practical assistance, local services, creative work and optional pathways into the wider project family.'),
 dict(id='P02',title='Aura of Intelligence',url='https://auraofintelligence.github.io/',repo='auraofintelligence.github.io',role='Personal intelligence and permissions',text='The personal digital-twin and cognitive-architecture development path. Mutual Futures describes proposed integration, not an already completed universal platform.'),
 dict(id='P03',title='P4A',url='https://p4a.xyz/',repo='p4a-xyz-cinema',role='Civic reflection and public scrutiny',text='Luke\'s proposed civic and political workbench: law memory, public records, simulations and examination of alternatives. Participation in a business is not political affiliation.'),
 dict(id='P04',title='P4A Oceania',url='https://auraofintelligence.github.io/p4a-oceania-cinema/index.html',repo='p4a-oceania-cinema',role='A regional exchange between distinct places',text='An exploratory route for locally authored experiments, care, culture, compute, resilience and learning across Oceania.'),
 dict(id='P05',title='Native Nations of the World',url='https://auraofintelligence.github.io/p4a-native-nations-cinema/index.html',repo='p4a-native-nations-cinema',role='Sovereign co-evolution',text='A workbench distinguishing established records from proposals. Nations retain their own names, authority, data rules and choice of participation.'),
 dict(id='P06',title='GAJRA Earth Infinity',url='https://auraofintelligence.github.io/GAJRA-earth-infinity/index.html',repo='GAJRA-earth-infinity',role='Alignment encounters and field tools',text='Meeting circles, practical reflection and exploration of Joyful Responsible Abundance through individual and collective perspectives.'),
 dict(id='P07',title='GAJRA Earth: meeting of minds',url='https://auraofintelligence.github.io/gajra-earth-claude-build/index.html',repo='gajra-earth-claude-build',role='Questions, reflection and shared memory',text='A complementary public conversation about human self-alignment and AI alignment, with questions, source trails and an evolving record.'),
 dict(id='P08',title="Australian Law 2012: Luke's Relevance",url='https://auraofintelligence.github.io/australian-law-2012-lukes-relevance/index.html',repo='australian-law-2012-lukes-relevance',role='Gather, Chomp, Sort, Plan',text='The original personal legal read-through, its public method, radical overcompliance and the design for a source-grounded legal engine.'),
 dict(id='P09',title='Australian Legal Engine',url='https://github.com/auraofintelligence/australian-legal-engine',repo='australian-legal-engine',role='Retrieval, citations and provision tracing',text='The companion code repository documents an offline provision parser and retrieval engine. Its README separates implemented functions from unfinished capabilities; this site has not independently audited its code.'),
 dict(id='P10',title='The Long Game: Grain by Grain',url='https://auraofintelligence.github.io/grain-by-grain-documentary/index.html',repo='grain-by-grain-documentary',role='A seven-generation civilisation horizon',text='A documentary planning project connecting useful local construction, materials, repair and learning with long-horizon habitats and civilisation continuity.'),
 dict(id='P11',title='Micronova and Excursions',url='https://auraofintelligence.github.io/micronova-and-excursions/index.html',repo='micronova-and-excursions',role='Threat inquiry and common preparations',text='A research workbench that separates observations, modelling, disputed mechanisms and cadence claims. Its shared-preparations approach informs resilience questions here, not a guaranteed disaster forecast.'),
 dict(id='P12',title='Global Founder Atlas',url='https://auraofintelligence.github.io/global-founder-atlas/index.html',repo='global-founder-atlas',role='International opportunities and partnerships',text='Funding, residencies, research placements, paid pilots and founder pathways. Individual opportunity dates, eligibility and terms need their own current source checks.'),
 dict(id='P13',title='Australian Visa & Activity Atlas',url='https://auraofintelligence.github.io/Australian-visa-activity-atlas/',repo='Australian-visa-activity-atlas',role='Entry and activity are separate questions',text='A source-led planning aid for Australian passport holders. It distinguishes entering a place from permission for work, teaching, performance, research or another proposed activity.'),
 dict(id='P14',title='Legal Memory Workbench',url='https://auraofintelligence.github.io/legal-memory-workbench/',repo='legal-memory-workbench',role='A personal legal surface',text='A neighbouring workbench for preparing structured, human-readable context about a person\'s own legal questions and sources.')
]
SOURCES = [
 dict(id='S01',title='Queensland Government: What is a co-operative',url='https://www.qld.gov.au/community/fair-trading/associations-charities-and-non-for-profits/cooperatives/what-is-a-cooperative',kind='Official guidance',checked='18 September 2026',text='Describes member ownership, sharing of benefits and losses, distributing and non-distributing co-operatives, and the one-member-one-vote structure. It does not approve this proposed organisation.'),
 dict(id='S02',title='ACCC: Thresholds for notifying acquisitions',url='https://www.accc.gov.au/business/mergers-and-acquisitions/thresholds-for-notifying-acquisitions',kind='Official guidance',checked='18 September 2026',text='Explains notification thresholds, exemptions and cumulative treatment of some acquisitions. Thresholds apply from 1 January 2026 unless otherwise stated. A mutual purpose is not itself a general exemption.'),
 dict(id='S03',title='Australian Electoral Commission: Referendums',url='https://www.aec.gov.au/elections/referendums/',kind='Official guidance',checked='18 September 2026',text='Describes the parliamentary and referendum process and the double-majority requirement. It does not announce a cyber-republic referendum in 2031.'),
 dict(id='S04',title='DFAT: Treaties',url='https://www.dfat.gov.au/international-relations/treaties',kind='Official source gateway',checked='18 September 2026',text='Gateway to Australian treaty information. Treaty status, reservations, entry into force and domestic implementation need separate records.'),
 dict(id='S05',title='Business Queensland: Due diligence when buying a business',url='https://www.business.qld.gov.au/starting-business/starting-buying/buying/due-diligence',kind='Official source gateway',checked='Source gateway; transaction-specific review required',text='A starting point for examining financial, operational, asset, contract and other information. No particular business has been verified by this website.'),
 dict(id='S06',title='Fair Work Ombudsman: When businesses change owners',url='https://www.fairwork.gov.au/employment-conditions/when-businesses-change-owners',kind='Official source gateway',checked='Source gateway; transaction-specific review required',text='Employment and transfer-of-business questions belong alongside ownership design. This is not a substitute for determining the rules of an actual transaction or placement.'),
 dict(id='S07',title='OAIC: Consent to handling personal information',url='https://www.oaic.gov.au/privacy/your-privacy-rights/your-personal-information/consent-to-the-handling-of-personal-information',kind='Official source gateway',checked='Source gateway; context-specific review required',text='Relevant background for consent and data handling. The local permissions builder is a design aid, not a legal consent service or a security implementation.'),
 dict(id='S08',title='Federal Register of Legislation',url='https://www.legislation.gov.au/',kind='Primary legislation',checked='Live register',text='Authoritative federal sources for checking exact provisions, compilations and commencement. A historical local archive is not a current consolidation.'),
 dict(id='S09',title='Queensland Legislation',url='https://www.legislation.qld.gov.au/',kind='Primary legislation',checked='Live register',text='Queensland legislation and historical versions. Local-government instruments, contracts and judicial interpretation remain separate source layers.'),
 dict(id='S10',title='Therapeutic Goods Administration',url='https://www.tga.gov.au/',kind='Official source gateway',checked='Source gateway; device-specific review required',text='Medical-device and therapeutic-goods enquiries require current, device-specific information. This workbench does not publish a treatment protocol or claim an approved Aura Geode exists.'),
 dict(id='S11',title='National Health and Medical Research Council',url='https://www.nhmrc.gov.au/',kind='Official source gateway',checked='Source gateway; study-specific review required',text='Research ethics and clinical evidence development are separate from benefit promises in an acquisition model.'),
 dict(id='S12',title='NOAA Space Weather Prediction Center',url='https://www.swpc.noaa.gov/',kind='Scientific source gateway',checked='Live source; no forecast reproduced here',text='Operational space-weather information. Linking this source does not substantiate every disputed hypothesis in the associated research projects.'),
 dict(id='S13',title='USGS Earthquake Hazards Program',url='https://www.usgs.gov/programs/earthquake-hazards',kind='Scientific source gateway',checked='Live source; no prediction reproduced here',text='Earthquake observations and research. A proposed prediction experiment is not presented here as an operating warning service.'),
 dict(id='S14',title='Smartraveller',url='https://www.smartraveller.gov.au/',kind='Official source gateway',checked='Live source; no destination advice reproduced here',text='Travel advice is time- and destination-specific. The travel room links to the user\'s activity atlas rather than inventing current visa rules.'),
 dict(id='S15',title='GitHub: Configure Pages action',url='https://github.com/actions/configure-pages',kind='Official implementation source',checked='18 September 2026',text='Pages deployment configuration. Initial enablement can require permissions beyond the workflow GITHUB_TOKEN; the deployment record reports the actual outcome.')
]

PAGES = []
from pathlib import Path
for chapter_file in sorted((Path(__file__).parent / "chapters").glob("*.py")):
 exec(compile(chapter_file.read_text(encoding='utf-8'), str(chapter_file), "exec"), globals())

TIMELINE = [('2026','The public workbench','Publish the architecture, source shelf and bounded tools. Establish a verified view of potential participating businesses rather than rely on exploratory marketplace counts.','Current website; proposed operating work'),
('Next operating stage','An actual succession and upgrade','A negotiated acquisition or partnership, with funding, management, employee arrangements, permitted data and a measurable transition plan. No transaction is announced here.','Proposed; no fixed date'),
('Learning network','Work, rest and knowledge transfer','Test paid learning, supervised rotations, management continuity, shared services and funded time away. Record outcomes before generalising.','Proposed; evidence-dependent'),
('No later than 2031',"Luke's legal-reflection and referendum horizon",'Luke proposes comprehensive reflection on Australian law and international obligations before a cyber-republic referendum by 2031. It is not an announced referendum, an entitlement to one or a forecast of an outcome.',"Author's proposed horizon"),
('2032','A capability and cultural horizon',"Explore links with Brisbane's wider learning, events and volunteer context. This workbench claims no official Olympic or Paralympic partnership.",'Project horizon; no partnership claimed'),
('July 2035','GAJRA Earth: Past, Present, Future','The proposed global art, music and reflection convergence around the 50th anniversary of Live Aid, with communities choosing their own participation.','Proposed gathering'),
('Seven generations and beyond','Continuity and outward exploration','Long-lived infrastructure, habitats, knowledge, culture and Kardashev galactic games remain a horizon for research, imagination and progressively demonstrated capability.','Long-horizon exploration')]
