PAGES.extend([
 dict(slug='index',label='Start here',title='Shared wealth.<br><em>Open horizons.</em>',intro='A public workbench connecting business succession to mutual ownership, universal intelligence, more possible lives and a future humanity can keep exploring.',kicker='Mutual Futures / a Strange but True workbench',image='home',accent='gold',type='home',sections=[
 sec('An ownership transition.<br>A much larger horizon.','The starting question is practical: could viable businesses with existing staff and clients pass from retiring proprietors into mutual ownership, while their people and operating systems develop together? Luke Nathan Hayes connects that question to adequate livelihoods, lawful civic reflection, health research, existential resilience and freedom to travel, create and rest.',statement='Preserve what people built. Expand what people can become.',refs=['P01','P02','P10']),
 sec('Four ways into the workbench.',cards=[card('The productive base','Business succession, member wealth, finance and upgrading.','succession.html'),card('More possible lives','Try Everything Once, Intermittent Retirement, adequate income and personal intelligence.','workforce.html'),card('A society that can adapt','Legal reflection, simulations, health, resilient operations and sovereign cooperation.','law.html'),card('The long game','Civilisation continuity, Kardashev galactic games, travel, culture and world-stage exchange.','galactic.html')]),
 sec('Tools to think with. Not promises to rely on.',cards=[card('Capital & cash-flow explorer','Change the purchase, finance and cash assumptions. See the funding gap and room for transition.','capital.html#tool'),card('Work & life planner','Sketch a cycle of employment, learning, care, travel and rest. Download your own Markdown plan.','workforce.html#tool'),card('Dependency studio','Trace how an interruption could travel through a small illustrative service network.','simulation.html#tool'),card('Personal permissions builder','Separate inference, training, sharing and retention in a portable draft.','intelligence.html#tool')]),
 sec('A workbench, not a completed institution.',"Mutual Futures is Luke's proposed architecture, published for examination and development. It is not an investment offer, a verified acquisition portfolio, an income entitlement, an approved medical service or an announced constitutional referendum. The source library retains the distinction between working papers and demonstrated results.",refs=['P03','P07'])]),
 dict(slug='succession',label='Business succession',title='A fair exit.<br><em>A shared beginning.</em>',intro='Existing teams. Existing clients. Productive assets and knowledge worth carrying forward. The question is who owns the next chapter.',kicker='01 / Productive continuity',image='succession',accent='gold',sections=[
 sec('The proposed acquisition universe.','The focus is established operating businesses with non-owner staff, customers and an evidenced trading history. New franchise territories, licence packages, empty fit-outs and registration-only shells are outside this brief. An operating franchise resale is a separate consideration, not the default target. No market count from the earlier exploratory conversation is treated as a verified inventory.',cards=[card('People and relationships','Who does the work, who holds the knowledge and which customer relationships depend on the departing owner?'),card('A business that can continue','What remains after properly costing replacement management, maintenance, employment obligations and working capital?'),card('A seller who chooses the terms','Cash, deferred consideration, retained interests and paid mentoring can be explored without assuming the owner wants to finance retirement risk.')],refs=['S05']),
 sec('Pay for the past. Decide who owns the future.','At a fair purchase price, the seller exchanges an operating asset for agreed consideration. The buyer also acquires obligations and risk. Wealth is not created merely by signing the contract. The intended change is who participates in future earnings, retained value and the gains from successful upgrading.',flow=[('Discover',"Identify an actual business and the seller's desired exit."),('Understand','Verify earnings, staff, contracts, assets and operating dependencies.'),('Agree','Negotiate ownership, finance and a funded transition.'),('Transfer','Support the team, customers and the knowledge handover.'),('Develop','Measure what improves and retain capacity for correction.')]),
 sec('Succession with a knowledge handover.','Mentoring would be a defined, paid relationship rather than an indefinite expectation that the seller rescues the business. Experienced employees help identify what matters: the reasons behind a quote, the exception in a maintenance process, the supplier who can source an unusual part. Documentation preserves useful knowledge without assuming every inherited practice deserves to remain.',table={'headers':['Before transfer','Question for the next chapter'],'rows':[['Owner-centred decisions','Which responsibilities can a capable management team genuinely assume?'],['Informal operating memory','What should be recorded, taught, tested and revised?'],['Customer goodwill','Which contracts, consents and relationships support continuity?'],['Technology backlog','Which improvements help the business without disrupting essential service?']]}),
 sec('Clusters, not indiscriminate accumulation.','A cluster could connect complementary capabilities such as maintenance, fabrication, logistics and software. Another could connect food production, distribution and catering. Acquisition count is not the achievement; viable service, member-attributable wealth and expanded human capability are the proposed measures.',callout="A proposed mutual purpose does not remove acquisition-law questions. The ACCC's current framework includes cumulative thresholds for some serial acquisitions.",refs=['S02'])]),
 dict(slug='ownership',label='Mutual wealth',title='Own the future.<br><em>Together, by choice.</em>',intro='Mutual wealth has substance when the people involved understand what they own, how decisions are made, who carries risk and what remains for those who come next.',kicker='02 / Ownership and stewardship',image='ownership',accent='mint',sections=[
 sec('Three connected functions.',"The architecture distinguishes local trading businesses, shared succession and investment capacity, and a sustainable employment and training function. They can cooperate without becoming one institution that owns a person's employer, health records, identity and civic choices.",cards=[card('Operating businesses','Continue serving customers through capable local management, with clearly defined member participation.'),card('Shared investment capacity','Assess acquisitions, arrange capital, retain reserves and disclose charges, responsibilities and conflicts.'),card('ready SET Co-op','The proposed ready sustainable employment and training cooperative connects paid learning, placements, shared equipment and transition support.')],refs=['D03','D05']),
 sec('A mutual is more than a future promise.','Queensland guidance distinguishes distributing co-operatives, which can return eligible surplus to members, from non-distributing co-operatives, which do not distribute profits to members. Its distributing model uses one member, one vote. The legal form for this proposal remains a design decision rather than a registration claim.',refs=['S01']),
 sec('The ownership questions stay visible.',table={'headers':['Question','What a public design would clarify'],'rows':[['Membership','How workers, customers, local businesses and communities relate to the assets.'],['Current benefits','How wages, eligible distributions, services and shared facilities are funded.'],['Future members','Which reserves and assets remain collective rather than being exhausted by the current cohort.'],['Moving or resting','What happens to membership and accrued interests during a placement or agreed sabbatical.'],['Leaving','How any individual financial interest is valued and settled without pretending all shared reserves are withdrawable.'],['Decision-making','Member authority, delegated management, review, conflicts and amendments. No founder veto or other veto power is proposed.']]}),
 sec('Connection without ingestion.','First Nations retain authority over their own participation and knowledge. Individuals retain their private Aura and the permissions they choose. Commercial ownership does not amount to ownership of people, cultures or communities. Shared services and intellectual-property licences would have transparent terms rather than unexplained permanent dependency.',statement='The federation can own assets. It does not own the lives built around them.',refs=['P05','P06','D09'])])
])
