PAGES.extend([
 dict(slug='capital',label='Capital & finance',title='Fund the transfer.<br><em>Leave room to grow.</em>',intro='Succession capital, operating resilience and transition investment are different requirements. A purchase that consumes all three leaves little space for the intended transformation.',kicker='03 / Financial workbench',image='capital',accent='gold',tool='capital',sections=[
 sec('Three uses of capital.',cards=[card('Succession','The negotiated purchase and transaction expenses.'),card('Operating resilience','Payroll liquidity, inventory, maintenance and interruption capacity.'),card('Transition','Systems, equipment, paid learning, mentoring and implementation.')]),
 sec('Little founder cash is not no capital.','A seller note defers part of the purchase price; it is not cash received by the business. Investor and member contributions supply capital on agreed terms. Loans require repayment. A guarantee supports a financing arrangement but is not cash available at settlement. An earn-out is contingent consideration and is not modelled as guaranteed funding here.',callout='The calculator uses invented inputs for arithmetic only. It is not a finance approval, valuation, tax model or estimate of a particular business. No actual seller, lender or investor has agreed to these terms.'),
 sec('What the model includes, and leaves open.','The tool compares total uses of capital with cash finance plus the deferred seller price. It calculates level annual repayments on the two illustrated loans, then examines base and stressed cash after debt service and the proposed annual workforce budget. The annual cash input is assumed to be after tax, ordinary operating costs, management pay, maintenance and working-capital requirements, but before acquisition financing and the added workforce budget. Investor distributions, fees, interest-only periods, refinancing, earn-outs and changes in tax are not forecast.',refs=['S05','D05']),
 sec('Growth and benefits draw on the same surplus.','The proposed mutual would decide how much available cash supports resilience, upgrading, current participants and the next acquisition. Finishing an acquisition loan creates an opportunity to revisit that allocation; it does not automatically create a universal income entitlement.',statement='A funding gap is a design question. A hidden funding gap is a failure of the model.')]),
 dict(slug='workforce',label='Work & life',title='More skills.<br><em>More possible lives.</em>',intro='Try Everything Once and Intermittent Retirement connect stable participation with the freedom to learn across sectors, change direction, travel, care and rest.',kicker='04 / Human capability',image='workforce',accent='mint',tool='workforce',sections=[
 sec('Breadth without compulsory restlessness.',"Luke's workforce proposal connects experience across care, food, energy, logistics, repair, coding, creative production and civic activity. The invitation is not to make everyone an expert in everything. Some people will keep a profession they love; others may discover one by trying several. Existing specialists remain essential to teaching and safe practice.",cards=[card('A home base','A stable employment relationship and a team to return to, where the actual arrangement supports it.'),card('A wider field',"Paid, supervised placements and learning with responsibilities suited to the participant's competence."),card('A next chapter','A pathway into another role, a return to the original one, entrepreneurship or an agreed period away.')],refs=['P03','D01']),
 sec('Intermittent Retirement is a funding question as well as a time question.','The proposal treats rest, family, recovery, learning and travel as legitimate phases throughout life. Funded time away depends on income, coverage and an agreed arrangement. Minutes saved by software are not automatically cash savings or a leave entitlement. The work-and-life planner below sketches preferences, not approved rosters or benefits.',refs=['P03','D01']),
 sec('ready SET Co-op as a connecting function.',"The proposed cooperative could coordinate learning records, mentors, host organisations, equipment, paid release, handovers and return pathways. A person's private interests and health history need not become a shared employer dossier. Information relevant to a role can remain separate from the person's deeper Aura.",refs=['D03','P02']),
 sec('Employment is still employment.','A proposed placement needs an actual arrangement for supervision, pay, insurance, responsibilities and continuity of entitlements. A community contribution receipt is not a substitute for wages. The Fair Work source is a starting point for transfer-of-business questions, not an automatic legal solution for this proposed network.',refs=['S06','D05'])]),
 dict(slug='livelihoods',label='Intelligence & income',title='Intelligence for everyone.<br><em>Income that is adequate.</em>',intro="Luke's proposal pairs universal intelligence with universal adequate income. The aim is not merely access to software, or a new label for one predetermined cash-payment model.",kicker='05 / Capability and sufficiency',image='livelihoods',accent='violet',sections=[
 sec('Two aims, held together.',cards=[card('Universal intelligence','Practical access to AI, learning, creation, simulation and the capacity to understand and change the systems a person uses.'),card('Universal adequate income',"An adequacy objective for people's actual lives, including through changes in work, care, learning and retirement."),card('More agency','Material security and usable intelligence that expand choice without requiring one model, employer, culture or worldview.')]),
 sec('The adequacy design remains open.','An income objective needs a definition of adequacy, a population, funding arrangements and a way to account for different circumstances. Household composition, disability, caring responsibilities, housing costs and place can affect the question. This site does not announce a payment amount, entitlement or eligibility rule.',table={'headers':['Design question','Why it matters'],'rows':[['Who is included?','A universal objective includes people outside any acquired business or member network.'],['What is adequate?','The proposed benchmark needs an intelligible basis and a way to reflect real circumstances.'],['How is it funded?','Trading surplus, services and other possible mechanisms are different sources, not interchangeable promises.'],['What changes over time?','Prices, needs, productive capacity and technology change; the model needs revision rather than a fixed slogan.'],['Who decides and reviews?','People affected need understandable choices, explanations and routes to challenge mistakes.']]}),
 sec('A productive base is a contribution, not the entire answer.','Mutual businesses could supply income, assets, shared services, equipment and learning. Member wealth and universal adequacy are different scopes. The strategy therefore distinguishes what a trading organisation can actually provide from the wider social arrangements being proposed.',statement='More output is one possible result. More security, capability and freely chosen time are the questions this proposal asks of it.'),
 sec('Three accounts, not one invented exchange rate.','The market account records money, wages, debt, costs and investment. The reciprocity account records verified voluntary contribution. A third account records outcomes such as learning, resilience and access. In the later source framing, one C-Hour records one verified hour; it is not priced in dollars or used as a wage. This site preserves that distinction while leaving legal and tax treatment to an actual, properly examined arrangement.',refs=['D05','D09'])])
])
