PAGES.extend([
 dict(slug='intelligence',label='Aura & intelligence',title='Your intelligence.<br><em>Your permissions.</em>',intro="Aura of Intelligence is the personal layer. Business, civic and scientific systems can connect to it without silently acquiring a person's inner life.",kicker='06 / Self-sovereign participation',image='intelligence',accent='violet',tool='permissions',sections=[
 sec('A personal architecture, not an employer profile.','Luke describes Aura of Intelligence as a developing cognitive architecture and digital twin of body and mind. The standard geometry is seven horn tori, each with a 12 by 24 matrix; alternative resolutions remain part of the design. The inside is private and the outside permissioned for sharing. People associate and combine their own facets, programmes and loops rather than receive one compulsory categorisation.',callout="The Aura of Intelligence Keystone of Consciousness remains the canonical name of Luke's proposed mechanism. This site does not claim that machine consciousness or the physical embodiment has been demonstrated.",refs=['P02']),
 sec('The legal work exists beside the app.','Luke reports that the legal layer has not yet been integrated into the Aura app demo. The Australian Law 2012 project publishes the method and design; the Australian Legal Engine repository separately documents implemented retrieval and provision-tracing functions. Future integration is a workstream, not a missing history.',refs=['P08','P09']),
 sec('Separate permissions for separate purposes.','A person may distinguish inference from training, local use from external sharing, temporary processing from retention, and personal records from professional or collective material. The builder below expresses those distinctions as a portable draft. It does not enforce access controls, implement cryptography or create a legally sufficient consent arrangement.',cards=[card('Personal',"The person's own values, memories, choices and preferred models."),card('Professional','The qualifications and relevant information a role genuinely requires.'),card('Collective','Material whose custodians or communities determine the relevant authority and permissions.')],refs=['P02','P05','S07']),
 sec('Humans, AI and robots in an intelligible relationship.','In the proposed operating model, a task has a purpose, authorisation, required competence, inputs, resources, dependencies, review and recovery path. Roles can change as capabilities develop. More automation does not by itself resolve who is responsible for an outcome.',statement='Coherence is not one central mind. It is a relationship people can understand, negotiate and revise.')]),
 dict(slug='law',label='Legal reflection',title='Understand the rules.<br><em>Examine what comes next.</em>',intro="Radical overcompliance is Luke's proposed transition method: operate within current obligations, make their effects legible, and use lawful processes to examine change.",kicker='07 / The legal layer',image='law',accent='gold',sections=[
 sec('A method with a history.',"Australian Law 2012: Luke's Relevance documents his 2012 to 2013 personal legal read-through and the Gather, Chomp, Sort, Plan method. Its public design connects source-grounded information with reflection and lawful reform. This site reports that lineage rather than treating overcompliance as a new procurement checklist.",refs=['P08']),
 sec('Three views that remain separate.',cards=[card('Current obligations and rights','Applicable sources, jurisdiction, commencement, version and unresolved interpretation.'),card('Voluntary commitments','Additional practices an individual or organisation has chosen, clearly distinguished from legal requirements.'),card('Proposed changes','Alternative wording or arrangements, assumptions, consultation and modelled consequences.')]),
 sec('A complete reflection is wider than a statute index.',"The intended scope includes Commonwealth, state and territory legislation; subordinate instruments; local laws and planning; judicial interpretation; relevant contracts and standards; and international treaties and obligations. A working map would retain the distinction between a source's wording, its legal status and an interpretation of what it means in context.",table={'headers':['Record','Questions carried with it'],'rows':[['Law and instruments','Which jurisdiction, version, commencement and affected provisions?'],['Judicial interpretation','Which court, issues, reasoning and subsequent treatment?'],['International commitments','Signature, ratification, entry into force, reservations and domestic implementation?'],['Proposed reform','Which rights, duties, institutions and dependencies would change?'],['Public reflection','Whose questions, alternative models and unresolved disagreements remain visible?']]},refs=['S04','S08','S09']),
 sec("2031 is Luke's proposed horizon.",'Luke aims for reflection on Australian law and international obligations before a proposed cyber-republic referendum no later than 2031. This is not an announced referendum or a forecast of its outcome. The AEC explains that constitutional alteration requires the applicable parliamentary process and approval at a referendum, including a double majority. The simulation would inform consideration, not enact a constitutional change.',refs=['P03','P08','S03']),
 sec('Reflection without a predetermined public verdict.','The workbench can compare proposed arrangements, including retaining existing ones, and expose their assumptions and consequences. Employment, healthcare, member benefits and access to tools remain distinct from political agreement. The page does not recommend a vote, candidate or party.',statement='Current law, personal commitments and a proposed future are three different kinds of statement.')]),
 dict(slug='simulation',label='Simulation studio',title='See the connections.<br><em>Rehearse the changes.</em>',intro='A proposed society-wide simulation architecture connects what keeps life operating with the people, AI and machines that can act, adapt and recover.',kicker='08 / Operational intelligence',image='simulation',accent='mint',tool='dependencies',sections=[
 sec('Model relationships, not just objects.','A food system depends on water, energy, transport, skills, refrigeration and information. An income system depends on actual resources and productive activity. A proposed reduction in working hours interacts with demand, qualifications and service coverage. The architecture asks what changes together rather than assuming each reform or upgrade is isolated.',flow=[('Observe','Record conditions, provenance and what remains unknown.'),('Model','Expose relationships and alternative assumptions.'),('Rehearse','Explore normal operation, changes and disruptions.'),('Act','Authorised people and systems carry out suitable work.'),('Review','Compare the outcome, correct and share agreed learning.')],refs=['D09','P10']),
 sec('Comprehensive scope is not perfect prediction.','The intended coverage can encompass society while individual models remain incomplete and uncertain. Each model would carry a purpose, data boundary, validation history, assumptions and failure conditions. A visually convincing digital twin is not, on that basis alone, a validated forecast.',cards=[card('Operating reality','What actually exists, who maintains it and what observations support the representation.'),card('Alternative futures','Changes to staffing, ownership, infrastructure, rules and resource allocation.'),card('Contingencies','Loss of suppliers, equipment, networks, finance, skills or access to a particular AI service.')],refs=['D03','D09']),
 sec('A small demonstrator, openly bounded.','The tool below uses a fixed illustrative graph. Selecting an unavailable service traces dependent services. It has no live sensors, geography, probability estimates, capacity model or emergency authority. Its value is showing the difference between a direct interruption and a dependency path. It is not a safety assessment.'),
 sec('Feedback from actual organisations.','Participating businesses could supply permitted operating observations and test specific improvements. Shared learning would not require pooling all customer, employee or cultural data. A useful loop records both improvements and failures, including a change that looked attractive in simulation but did not work in practice.',refs=['P02','P05','D05'])])
])
