PAGES.extend([
 dict(slug='health',label='Health & care',title='Health to live.<br><em>Time to enjoy it.</em>',intro='The health surge belongs to a wider life, not a requirement that people optimise themselves for an employer, a civic platform or an AI system.',kicker='09 / Care, access and research',image='health',accent='mint',sections=[
 sec('Ordinary care and research are related, not interchangeable.',"Luke's later Vuvale submission begins civic health with food, sleep, movement, cleaner environments, accessible information and individual control of health data. It separately describes research into shared preventive and restorative facilities, including sauna, regulated hyperbaric oxygen therapy and the Aura Geode development path.",cards=[card('Access and everyday support','Care, understandable information, appropriate services and working arrangements that leave room for life.'),card('Shared facilities','Ownership, staffing, utilisation, safety, upkeep and access arrangements examined as part of an actual service.'),card('Research pathways','Device engineering, clinical questions, ethics, evidence, professional responsibilities and independent review.')],refs=['D05','D09']),
 sec('The Aura Geode is a development path.','The proposal connects an engineering concept, shared ownership, personal digital-twin research and possible health applications. This site does not provide a treatment protocol, claim an approved device exists or infer a guaranteed outcome from an early study. The older surge papers remain identifiable as their own working documents rather than silently becoming clinical evidence.',refs=['D01','D05','S10','S11']),
 sec('A separate financial case.','A member service may have income and costs. A research project may have research funding. A hoped-for reduction in future healthcare spending is a different claim. The later source framing keeps health savings outside the base financial case until research demonstrates them; it does not use an assumed medical transformation to justify acquisition debt.',statement='Health access is a purpose. An unverified health saving is not cash in the bank.',refs=['D05']),
 sec('Earn-to-Heal within the reciprocity proposal.','The source papers explore community-chosen wellbeing access in recognition of verified voluntary contribution. One C-Hour is a contribution receipt in the later framing, not a market wage or exchange rate. Consent to a study, eligibility for healthcare, employment and civic participation remain separate decisions.',refs=['D05','D09'])]),
 dict(slug='resilience',label='Existential resilience',title='Keep life possible.<br><em>Keep choices open.</em>',intro='The ambition includes helping humanity survive existential threats. The practical question is which capabilities support ordinary life, withstand disruption and preserve the ability to recover.',kicker='10 / Continuity across scales',image='resilience',accent='gold',sections=[
 sec('One field of inquiry, different kinds of evidence.',"Grain by Grain spans everyday disruption, global and cosmic risks, frontier research, and imaginative stress tests. Micronova and Excursions distinguishes observations, modelling, disputed mechanisms and cadence claims. These are the projects' research frames, not a verified forecast that one specific catastrophe is imminent.",cards=[card('Observed and operational','Records and services that can be checked against their primary sources.'),card('Modelled and contested','Explicit assumptions, competing explanations and tests that might change an assessment.'),card('Exploratory horizons','Long-term designs and imaginative scenarios labelled so they do not impersonate observations.')],refs=['P10','P11','S12','S13']),
 sec('Common preparations, multiple possible causes.','The Micronova and Excursions build page organises preparation around shared consequences rather than requiring agreement on every threat mechanism.',table={'headers':['Capability','Question carried into the business network'],'rows':[['Energy that can operate independently','What essential work continues when an external supply fails?'],['Water held, treated and cycled','What storage, treatment, power and expertise does continuity require?'],['Food and repair','What can be produced, stored, maintained and repaired locally?'],['Knowledge that stays','What records, methods and skills remain usable without the network?'],['Protective shelter','Which actual conditions is the structure designed and validated to withstand?'],['People who already know one another','Who has practised the relationships and handovers before a disruption?']]},refs=['P11']),
 sec('Distributed capability can still share a failure.','A network spread across many places may depend on one software update, supplier, financier or communications service. The proposed architecture therefore asks about failure isolation and substitutes as well as geographic distribution. Adding a backup in a diagram is different from demonstrating that it works.',refs=['D03','D04']),
 sec('The succession connection.','Acquired and participating businesses could preserve machine tools, trades, food logistics, health capability and operating knowledge. Upgrading could make some of that capability more robust. These purposes would be explicitly funded and agreed, not used to justify unlimited obligations on employees.',statement='Continuity includes repair, culture, knowledge and the freedom to develop beyond the plan that preserved it.',refs=['P10'])]),
 dict(slug='galactic',label='Kardashev galactic games',title='Civilisation as a beginning.<br><em>Not a finishing line.</em>',intro="Kardashev galactic games is Luke's expansive horizon: humanity developing the capability to explore, cooperate, create and continue beyond today's planetary limits.",kicker='11 / The long game',image='galactic',accent='violet',sections=[
 sec('Not merely space-themed retraining.',"The horizon includes actual scientific, material, energy, habitat and interplanetary capability, extending in imagination towards stellar and galactic scales. Nearer-term simulations, workshops and shared projects provide ways to begin learning. The phrase describes Luke's project horizon, not an operating galactic event or a schedule of assured technological milestones.",refs=['P10','P11']),
 sec('A capability path rather than one giant leap.','The documentary planning project begins with a proposed Dunwich gateway tunnel and useful material streams, moves through service corridors and subterranean industry, and holds a 20-million-person worldship as a long-horizon concept. Each stage is a proposal with its own engineering, environmental, cultural, financial and public questions. No excavation, settlement approval or completed worldship is claimed here.',flow=[('Useful local systems','Food, repair, communications and learning.'),('Connected infrastructure','Transport, materials, energy and protected services.'),('Long-lived habitats','Life-support, maintenance, culture and knowledge across generations.'),('Outward exploration','Scientific networks, remote systems and future off-world environments.')],refs=['P10']),
 sec('Make learning playable without making suffering a game.',"Grain by Grain's playbook offers participants, resources, branching skills, rehearsals and ways to preserve progress through setbacks. It distinguishes preparation from trauma and keeps participation voluntary. A simulated habitat, a tested component and an operating habitat are different accomplishments.",cards=[card('Explore','Enter a model, ask a question, compare assumptions and imagine possibilities.'),card('Develop','Build competence, validate a component or preserve knowledge another group can use.'),card('Connect','Share agreed learning, relationships and useful capabilities without imposing one path.')],refs=['P10']),
 sec('Survival in service of a life worth living.',"A long-lived civilisation would also carry music, art, relationships, nature, play and unstructured time. The purpose is not permanent emergency discipline. Joyful Responsible Abundance is Luke's organising question for what increasing capability is for, with room for different answers.",statement='The games can widen the horizon. The person keeps the choice of whether, where and how to play.',refs=['P06','P07','P10'])])
])
