PAGES.extend([
 dict(slug='travel',label='World travel',title='A world to learn from.<br><em>A life to enjoy.</em>',intro='Travel, residencies, research, relationships, creativity and time without an agenda belong inside the life design. They do not all need to justify themselves through productivity.',kicker='12 / Mobility and experience',image='travel',accent='gold',sections=[
 sec('Two atlases, different questions.',cards=[card('Global Founder Atlas','Where could a project and a person develop together? Funding, residencies, research placements, partnerships and paid pilots.','https://auraofintelligence.github.io/global-founder-atlas/index.html'),card('Australian Visa & Activity Atlas','What does the intended journey actually permit? Entry and the planned activity are examined separately.','https://auraofintelligence.github.io/Australian-visa-activity-atlas/')],refs=['P12','P13']),
 sec('A pathway, not a current visa assurance.','The activity atlas is designed for Australian passport holders. The wider workforce concept would need additional pathways for people with different citizenships and circumstances. This site does not reproduce unverified visa rules, funding deadlines or destination advice. Each actual journey has its own current sources and preparation.',table={'headers':['A journey might involve','A distinct preparation question'],'rows':[['Tourism and time away','Entry, duration, practical support and current destination advice.'],['Meetings or a conference','The intended activity, host invitation and applicable conditions.'],['Teaching, speaking or creative work','Whether that specific activity and any payment are permitted.'],['Research or a pilot','Host arrangements, project responsibilities, data, equipment and intellectual property.'],['A longer base overseas','The relevant residence, work, tax, insurance and business questions.']]},refs=['P13','S14']),
 sec('A network can travel without losing its home.','International placements and collaborations could connect participants with facilities, cultures and expertise that are not all available in one region. Some people would travel; some would host; others would stay rooted and connect through visiting collaborators and digital environments. Local identity and the ability to return would remain part of the design.'),
 sec('Fun is not a productivity loophole.',"Intermittent Retirement might include family, music, a festival, learning a language, friendship, curiosity or doing very little. A period away does not become a compulsory field assignment. The same architecture that supports scientific work can also leave space for a person's own reasons to explore.",statement='Travel can create capability. It can also simply be a life someone wants to live.',refs=['P10','P12'])]),
 dict(slug='oceania',label='Oceania & Native Nations',title='Many sovereign centres.<br><em>Shared possibilities.</em>',intro="The wider pattern is offered for locally chosen participation. Queensland, Oceania, Native Nations and international partners are not branches of one founder's authority.",kicker='13 / Federation without assimilation',image='oceania',accent='mint',sections=[
 sec('A connection does not require the same institution.','P4A Oceania describes a Minjerribah seed, an Australian ripple and an Oceanian horizon. Its extension here would be exchange between independently authored experiments, not an Australian franchise expansion. Each place could retain its own governance, language, rules, sources and chosen priorities.',refs=['P04','D05','D06']),
 sec('Native Nations author their own participation.','The Native Nations workbench distinguishes established records from proposals and centres self-naming, control of contributed material and refusal. A Nation might share a public teaching method without sharing its underlying cultural knowledge. Another might contribute a question without joining any commercial structure.',statement='Nations are not subsidiaries. Personal and collective permissions remain different kinds of authority.',refs=['P05','D09']),
 sec('Money, contribution and outcomes stay distinct.','The later Vuvale paper describes an account for money, an account for voluntary contribution and an account for wider outcomes. The framework can be examined locally without presuming that a C-Hour has already acquired a special legal or tax status. A proposal about a treaty relationship is not the treaty itself.',cards=[card('Money','Actual funding, earnings, costs, wages, repayments and retained value.'),card('Contribution','Verified voluntary activity and benefits chosen within a defined community arrangement.'),card('Outcomes','Skills, access, resilience, research findings and what people chose to change or stop.')],refs=['D05','D06']),
 sec('GAJRA Earth as a voluntary connection.',"The Global Association for Joyful Responsible Abundance on Earth is Luke's proposed connective layer for reflection, culture, science and learning. The garland is a useful image: distinct flowers connected by a thread, not melted into one substance. Its role here is exchange, not a global authority or a claim to speak for all participants.",refs=['P06','P07','D09'])]),
 dict(slug='culture',label='Culture & world stage',title='A future people can enter.<br><em>Not just watch.</em>',intro='Film, music, art, gatherings and shared stories make the work legible. They also have value beyond explaining a financial or technical programme.',kicker='14 / Public imagination',image='culture',accent='violet',sections=[
 sec('Real work, public learning, voluntary stories.',"Strange but True can connect ordinary practical help with filmmaking, music and public explanation. A participating business might document a useful change, a failed experiment or a person's new chapter. Appearing on camera would remain separate from employment or membership.",refs=['P01','P10']),
 sec('Three public rooms.',cards=[card('What exists','Demonstrated tools, actual work, published results and a source trail.'),card('What is being tried','Experiments, costs, setbacks, unanswered questions and revisions.'),card('What is imagined','Music, film, speculative environments and possible futures clearly identified as such.')]),
 sec('2032 and 2035 as project horizons.',"Luke's wider documents use Brisbane 2032 as a learning and capability horizon, without this site claiming an official Games partnership. GAJRA Earth proposes a July 2035 convergence around the 50th anniversary of Live Aid, with art, music and reflection across Past, Present and Future. These are proposed project connections, not confirmed event bookings.",table={'headers':['Theme','A question for participating people'],'rows':[['Past','What have we inherited, learned, preserved and reconsidered?'],['Present','How are people actually living, working, caring and choosing?'],['Future','What would we like to explore next, and with whom?']]},refs=['D04','P06','P07']),
 sec('Optimism with a visible record.',"The public story would include what people refused, what did not work and what remains financially or technically unresolved. A better-looking dashboard is not the same as a benefit reaching someone's life. The documentary role is to make those differences visible, not conceal them.",statement='More possible lives is the invitation. Real outcomes are the evidence.')])
])
