PAGES.extend([
 dict(slug='about',label='About this workbench',title='Mutual Futures.<br><em>A wider field of choice.</em>',intro='A standalone public project by Luke Nathan Hayes / Strange But True / Aura of Intelligence, developed from Minjerribah and South East Queensland with an outward-looking horizon.',kicker='18 / About and use',image='about',accent='violet',type='about',sections=[
 sec('The proposition in full.','Mutual Futures explores voluntary succession of existing staffed businesses into mutual wealth, while preserving customer relationships and upgrading practical capability. It connects that productive base with Try Everything Once, Intermittent Retirement, universal intelligence and universal adequate income; a personal Aura and permissions layer; legal reflection and radical overcompliance; simulations of social and operational dependencies; civic health and research; existential resilience; sovereign cooperation across Oceania and Native Nations; world travel, culture and Kardashev galactic games.\n\nThe aim described by Luke is not only to own businesses or preserve jobs. It is to develop shared productive assets and human capability while widening the lives people can choose and helping humanity continue through major threats. This public workbench makes the relationships, tools, sources and open questions inspectable. It does not claim to speak for a government, community, First Nation, investor, medical institution or future participant.'),
 sec('Project status.',"This website is a public prototype and synthesis of Luke's project material, not a registered mutual, investment product, acquisition offer, clinical service, legal practice or government programme. The interactive tools run in the browser. They do not connect to an AI model, bank, payroll, identity provider, live sensor network or migration authority. The source shelf distinguishes what is published from what remains proposed."),
 sec('A personal project with optional connections.',"Public projects can express different facets of Luke's own Aura without claiming that his preferred future is everyone's. People may explore one room, adapt a useful pattern under the licence, disagree with the framing, or leave. Shared benefits, employment and access are not conditional on political agreement.",refs=['P02','P03','P06','P07']),
 sec('Data, local tools and publication.','The website has no account system, advertising, analytics, payment form or tracking script. Drafts remain in memory until a visitor chooses to save them in this browser or download them. Browser storage is not encryption. The site host receives normal web requests. External links open a new tab and their services have their own terms. An export belongs to its author, who chooses where to share it.'),
 sec('Credits and contact.','Concepts, source materials and project direction: Luke Nathan Hayes. This Mutual Futures website implementation: Luke Nathan Hayes with ChatGPT, September 2026. Reused illustrations are credited in the asset manifest and linked back to their source projects. Existing projects keep their original collaborator credits. No font files or SVG assets are bundled.\n\nPublic enquiries and correction suggestions: auraofintelligence@gmail.com. GitHub issues can also carry corrections, but a public issue is not a place for private business, health or identity records.')]),
 dict(slug='site-map',label='Site map',title='Every room.<br><em>Your own route.</em>',intro='The whole workbench, without a sign-up path or a prescribed order. Each chapter has its own page and a route to the next.',kicker='19 / Navigation',image='sitemap',accent='mint',type='sitemap',sections=[]),
 dict(slug='licence',label='Licence',title='Public to explore.<br><em>Rights kept clear.</em>',intro='Strange But True Public Source Licence. Non-commercial exploration with attribution, and separate written permission for commercial and institutional use.',kicker='20 / Licence',image='licence',accent='gold',type='licence',sections=[])
])
